# Generated by Django 3.1.2 on 2020-12-30 11:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('abreviatura', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('mercado_internacional', models.BooleanField(default=True)),
                ('mercado_nacional', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'db_table': 'in_commodities',
            },
        ),
        migrations.CreateModel(
            name='Leyendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('mercado', models.CharField(choices=[('N', 'NACIONAL'), ('I', 'INTERNACIONAL')], default='N', max_length=1)),
            ],
            options={
                'verbose_name': 'Leyenda de mercado',
                'verbose_name_plural': 'Leyendas de mercado',
                'db_table': 'in_leyendas',
            },
        ),
        migrations.CreateModel(
            name='ValoresMercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tipo_mercado', models.CharField(choices=[('N', 'NACIONAL'), ('I', 'INTERNACIONAL')], default='N', max_length=1)),
                ('par', models.CharField(choices=[('BS/USD', 'BS/USD'), ('BS/EUR', 'BS/EUR'), ('BS/PTR', 'BS/PTR'), ('BS/BTC', 'BS/BTC'), ('USD/PTR', 'USD/PTR'), ('EUR/PTR', 'EUR/PTR'), ('USD/G', 'USD/G'), ('USD/T', 'USD/T'), ('USD/QQ', 'USD/QQ'), ('USD/L', 'USD/L'), ('USD/L', 'USD/L'), ('USD/BARRIL', 'USD/BARRIL'), ('USD/BTC', 'USD/BTC')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('movilidad', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('mercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.commodities')),
            ],
            options={
                'verbose_name': 'Valor de mercado',
                'verbose_name_plural': 'Valores de mercado',
                'db_table': 'in_valores_mercado',
                'ordering': ['-fecha'],
            },
        ),
    ]
