# Generated by Django 3.1.2 on 2020-12-30 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoresmercado',
            name='fecha',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='valoresmercado',
            name='par',
            field=models.CharField(choices=[('BS/USD', 'BS/USD'), ('BS/EUR', 'BS/EUR'), ('BS/PTR', 'BS/PTR'), ('BS/BTC', 'BS/BTC'), ('USD/PTR', 'USD/PTR'), ('EUR/PTR', 'EUR/PTR'), ('USD/G', 'USD/G'), ('USD/T', 'USD/T'), ('USD/QQ', 'USD/QQ'), ('USD/L', 'USD/L'), ('USD/L', 'USD/L'), ('USD/BARRIL', 'USD/BARRIL'), ('USD/BTC', 'USD/BTC')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='valoresmercado',
            name='tipo_mercado',
            field=models.CharField(choices=[('N', 'NACIONAL'), ('I', 'INTERNACIONAL')], db_index=True, default='N', max_length=1),
        ),
    ]
