# Generated by Django 3.1.2 on 2020-12-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0003_valoresmercadoactual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoresmercadoactual',
            options={'ordering': ['-fecha'], 'verbose_name': 'Valor de mercado', 'verbose_name_plural': 'Valores de mercado'},
        ),
        migrations.AlterModelTable(
            name='valoresmercadoactual',
            table='in_valores_mercado_actual',
        ),
    ]
